### ISSUE TITLE
AddressSanitizer error in duckdb::SelectionVector::set_index(unsigned long, unsigned long) src/include/duckdb/common/types/selection_vector.hpp:86

### ISSUE THREAD

**Issue by fuzzerofducks** [duckdb/duckdb-fuzzer#132]
Issue found by SQLSmith on git commit hash [c8160](https://github.com/duckdb/duckdb/commit/c81600ed51613a884de33dd5cb830f0238956743) using seed 212842251.
### To Reproduce
```sql
create table all_types as select * exclude(small_enum, medium_enum, large_enum) from test_all_types();
SELECT ref_1.nested_int_array AS c0 FROM main.all_types AS ref_0 RIGHT JOIN main.all_types AS ref_1 INNER JOIN (SELECT subq_0.c0 AS c8 FROM main.all_types AS ref_2 , (SELECT ref_2.time_tz AS c0) AS subq_0) AS subq_1 ON ((ref_1."varchar" ^@ ref_1."varchar")) INNER JOIN main.all_types AS ref_4 ON ((subq_1.c8 = ref_4.time_tz)) ON (NULL)

```

### Error Message
```
AddressSanitizer error in duckdb::SelectionVector::set_index(unsigned long, unsigned long) src/include/duckdb/common/types/selection_vector.hpp:86
```

**Comment by Mytherin** [comment]
This seems to be a regression in the new TupleDataCollection related to handling of nested lists. CC @lnkuiper 

```bash
==57663==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00012231d614 at pc 0x000108757890 bp 0x00016d5a6590 sp 0x00016d5a6588
WRITE of size 4 at 0x00012231d614 thread T0
    #0 0x10875788c in duckdb::SelectionVector::set_index(unsigned long long, unsigned long long) selection_vector.hpp:86
    #1 0x107f5f30c in duckdb::TupleDataCollection::ListWithinListComputeHeapSizes(duckdb::Vector&, duckdb::Vector const&, duckdb::TupleDataVectorFormat&, duckdb::SelectionVector const&, unsigned long long, duckdb::UnifiedVectorFormat const&) tuple_data_scatter_gather.cpp:360
    #2 0x107f5bcdc in duckdb::TupleDataCollection::WithinListHeapComputeSizes(duckdb::Vector&, duckdb::Vector const&, duckdb::TupleDataVectorFormat&, duckdb::SelectionVector const&, unsigned long long, duckdb::UnifiedVectorFormat const&) tuple_data_scatter_gather.cpp:164
    #3 0x107f5b148 in duckdb::TupleDataCollection::ComputeHeapSizes(duckdb::Vector&, duckdb::Vector const&, duckdb::TupleDataVectorFormat&, duckdb::SelectionVector const&, unsigned long long) tuple_data_scatter_gather.cpp:134
    #4 0x107f06110 in duckdb::TupleDataCollection::ComputeHeapSizes(duckdb::TupleDataChunkState&, duckdb::DataChunk const&, duckdb::SelectionVector const&, unsigned long long) tuple_data_scatter_gather.cpp:73
```

Here is a more minimal example, which seems to work in v0.7.1:
```sql
CREATE TABLE all_types("varchar" VARCHAR, nested_int_array INTEGER[][]);;
INSERT INTO all_types VALUES('b',[[], NULL, [], [NULL]]);


SELECT ref_1.nested_int_array AS c0
FROM range(3) AS ref_0
RIGHT JOIN all_types AS ref_1
INNER JOIN (SELECT NULL AS c8 FROM range(3)) AS subq_1 ON (ref_1."varchar" = ref_1."varchar")
INNER JOIN range(3) AS ref_4(time_tz) ON (subq_1.c8 = ref_4.time_tz) ON (NULL);
```
