### ISSUE TITLE
AddressSanitizer error in duckdb::SelectionVector::set_index(unsigned long, unsigned long) src/include/duckdb/common/types/selection_vector.hpp:86

### ISSUE THREAD

**Issue by fuzzerofducks** [duckdb/duckdb-fuzzer#135]
Issue found by SQLSmith on git commit hash [d3562](https://github.com/duckdb/duckdb/commit/d3562b54ee03f4aaa000cf6700124f06d13a9d96) using seed 468799337.
### To Reproduce
```sql
create table all_types as select * exclude(small_enum, medium_enum, large_enum) from test_all_types();
SELECT ref_0.usmallint AS c0 FROM main.all_types AS ref_0 INNER JOIN main.all_types AS ref_1 ON (EXISTS(SELECT ref_1.nested_int_array AS c0, ref_1.tinyint AS c1 FROM main.all_types AS ref_2 WHERE ((CAST(NULL AS VARCHAR) !~~ ref_0."varchar") AND EXISTS(SELECT ref_1."struct" AS c0 FROM main.all_types AS ref_3 WHERE 1))))

```

### Error Message
```
AddressSanitizer error in duckdb::SelectionVector::set_index(unsigned long, unsigned long) src/include/duckdb/common/types/selection_vector.hpp:86
```

**Comment by Mytherin** [comment]
Reduced example:

```sql

CREATE TABLE nested(nested_int_array INTEGER[][]);
INSERT INTO nested VALUES([[42, 999]]);
SELECT (
	SELECT ref_1.nested_int_array
) AS c0
FROM range(3), nested AS ref_1;
```

Stack trace:

```cpp
    #0 0x123e734d0 in duckdb::SelectionVector::set_index(unsigned long long, unsigned long long) selection_vector.hpp:86
    #1 0x1262cc754 in duckdb::TupleDataCollection::ListWithinListComputeHeapSizes(duckdb::Vector&, duckdb::Vector const&, duckdb::TupleDataVectorFormat&, duckdb::SelectionVector const&, unsigned long long, duckdb::UnifiedVectorFormat const&) tuple_data_scatter_gather.cpp:372
    #2 0x1262c85e8 in duckdb::TupleDataCollection::WithinListHeapComputeSizes(duckdb::Vector&, duckdb::Vector const&, duckdb::TupleDataVectorFormat&, duckdb::SelectionVector const&, unsigned long long, duckdb::UnifiedVectorFormat const&) tuple_data_scatter_gather.cpp:164
    #3 0x1262c791c in duckdb::TupleDataCollection::ComputeHeapSizes(duckdb::Vector&, duckdb::Vector const&, duckdb::TupleDataVectorFormat&, duckdb::SelectionVector const&, unsigned long long) tuple_data_scatter_gather.cpp:134
    #4 0x126273e84 in duckdb::TupleDataCollection::ComputeHeapSizes(duckdb::TupleDataChunkState&, duckdb::DataChunk const&, duckdb::SelectionVector const&, unsigned long long) tuple_data_scatter_gather.cpp:73
    #5 0x1262b73a0 in duckdb::TupleDataCollection::AppendUnified(duckdb::TupleDataPinState&, duckdb::TupleDataChunkState&, duckdb::DataChunk&, duckdb::SelectionVector const&, unsigned long long) tuple_data_collection.cpp:194
    #6 0x127e522d8 in unsigned long long duckdb::GroupedAggregateHashTable::FindOrCreateGroupsInternal<duckdb::aggr_ht_entry_32>(duckdb::AggregateHTAppendState&, duckdb::DataChunk&, duckdb::Vector&, duckdb::Vector&, duckdb::SelectionVector&) aggregate_hashtable.cpp:430
```
